spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: aaaa
      database: users
      port: 27017
      host: localhost
      connection-string: mongodb://localhost:27017/users?authSource=admin
  config:
    activate:
      on-profile: local